apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-rental-web
  labels:
    app: property-rental-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: property-rental-web
  template:
    metadata:
      labels:
        app: property-rental-web
    spec:
      containers:
        - name: property-rental-web
          image: phatnguyentan/property-rental-web:1.0.5
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: service-configmap
            - secretRef:
                name: service-secret
          ports:
            - name: http
              containerPort: 3000
      restartPolicy: Always


