apiVersion: v1
kind: Service
metadata:
  name: property-rental-web
  labels:
    app: property-rental-web
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: property-rental-web
  type: LoadBalancer
